package edu.opinion.common.db;



/**
 * TbAuRef generated by MyEclipse - Hibernate Tools
 */

public class TbAuRef  implements java.io.Serializable {


    // Fields    

     private String id;
     private TbUser tbUser;
     private TbAu tbAu;


    // Constructors

    /** default constructor */
    public TbAuRef() {
    }

    
    /** full constructor */
    public TbAuRef(TbUser tbUser, TbAu tbAu) {
        this.tbUser = tbUser;
        this.tbAu = tbAu;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public TbUser getTbUser() {
        return this.tbUser;
    }
    
    public void setTbUser(TbUser tbUser) {
        this.tbUser = tbUser;
    }

    public TbAu getTbAu() {
        return this.tbAu;
    }
    
    public void setTbAu(TbAu tbAu) {
        this.tbAu = tbAu;
    }
   








}