package edu.opinion.common.db;

import java.util.HashSet;
import java.util.Set;


/**
 * TbAu generated by MyEclipse - Hibernate Tools
 */

public class TbAu  implements java.io.Serializable {


    // Fields    

     private String id;
     private String au;
     private String ex;
     private Set tbAuRefs = new HashSet(0);


    // Constructors

    /** default constructor */
    public TbAu() {
    }

	/** minimal constructor */
    public TbAu(String au, String ex) {
        this.au = au;
        this.ex = ex;
    }
    
    /** full constructor */
    public TbAu(String au, String ex, Set tbAuRefs) {
        this.au = au;
        this.ex = ex;
        this.tbAuRefs = tbAuRefs;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getAu() {
        return this.au;
    }
    
    public void setAu(String au) {
        this.au = au;
    }

    public String getEx() {
        return this.ex;
    }
    
    public void setEx(String ex) {
        this.ex = ex;
    }

    public Set getTbAuRefs() {
        return this.tbAuRefs;
    }
    
    public void setTbAuRefs(Set tbAuRefs) {
        this.tbAuRefs = tbAuRefs;
    }
   








}