package edu.opinion.common.db;

import java.util.Date;

/**
 * TbSensitiveTopic generated by MyEclipse Persistence Tools
 */

public class TbSensitiveTopic implements java.io.Serializable {

	// Fields

	private String id;

	private TbCluster tbCluster;

	private TbReBbs tbReBbs;

	private TbParserNews tbParserNews;

	private TbParserBbs tbParserBbs;

	private TbReNews tbReNews;

	private Integer frequency;
	
	private String sensitiveWords;
	
	private String clustersId;
	
	private Date dealTime;

	// Constructors

	/** default constructor */
	public TbSensitiveTopic() {
	}

	/** full constructor */
	public TbSensitiveTopic(TbCluster tbCluster, TbReBbs tbReBbs,
			TbParserNews tbParserNews, TbParserBbs tbParserBbs,
			TbReNews tbReNews, Integer frequency) {
		this.tbCluster = tbCluster;
		this.tbReBbs = tbReBbs;
		this.tbParserNews = tbParserNews;
		this.tbParserBbs = tbParserBbs;
		this.tbReNews = tbReNews;
		this.frequency = frequency;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TbCluster getTbCluster() {
		return this.tbCluster;
	}

	public void setTbCluster(TbCluster tbCluster) {
		this.tbCluster = tbCluster;
	}

	public TbReBbs getTbReBbs() {
		return this.tbReBbs;
	}

	public void setTbReBbs(TbReBbs tbReBbs) {
		this.tbReBbs = tbReBbs;
	}

	public TbParserNews getTbParserNews() {
		return this.tbParserNews;
	}

	public void setTbParserNews(TbParserNews tbParserNews) {
		this.tbParserNews = tbParserNews;
	}

	public TbParserBbs getTbParserBbs() {
		return this.tbParserBbs;
	}

	public void setTbParserBbs(TbParserBbs tbParserBbs) {
		this.tbParserBbs = tbParserBbs;
	}

	public TbReNews getTbReNews() {
		return this.tbReNews;
	}

	public void setTbReNews(TbReNews tbReNews) {
		this.tbReNews = tbReNews;
	}

	public Integer getFrequency() {
		return this.frequency;
	}

	public void setFrequency(Integer frequency) {
		this.frequency = frequency;
	}

	public String getSensitiveWords() {
		return this.sensitiveWords;
	}

	public void setSensitiveWords(String sensitiveWords) {
		this.sensitiveWords = sensitiveWords;
	}

	public String getClustersId() {
		return clustersId;
	}

	public void setClustersId(String clustersId) {
		this.clustersId = clustersId;
	}

	public Date getDealTime() {
		return dealTime;
	}

	public void setDealTime(Date dealTime) {
		this.dealTime = dealTime;
	}
}