package edu.opinion.common.db;

import java.util.HashSet;
import java.util.Set;

/**
 * TbUser generated by MyEclipse Persistence Tools
 */

public class TbUser implements java.io.Serializable {

	// Fields

	private String id;

	private String account;

	private String password;

	private Set tbAuRefs = new HashSet(0);

	// Constructors

	/** default constructor */
	public TbUser() {
	}

	/** minimal constructor */
	public TbUser(String account, String password) {
		this.account = account;
		this.password = password;
	}

	/** full constructor */
	public TbUser(String account, String password, Set tbAuRefs) {
		this.account = account;
		this.password = password;
		this.tbAuRefs = tbAuRefs;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getTbAuRefs() {
		return this.tbAuRefs;
	}

	public void setTbAuRefs(Set tbAuRefs) {
		this.tbAuRefs = tbAuRefs;
	}

}